// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfltgoprxzzniaxcqter.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmbHRnb3ByeHp6bmlheGNxdGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MjY3ODAsImV4cCI6MjA1NzEwMjc4MH0.jVOs1QQ5M4XKn3x7y3wAiLl7ajgEvc7mpKkmqeCFDIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);